# image will be published to ghcr.io/<user>/<name>
name: fedora-bluebuild

# description will be included in the image's metadata
description: My personal Fedora Silverblue image based on universal-blue main image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# the tags to use
alt-tags:
  - latest

# stages. See: https://github.com/blue-build/cli/pull/173
stages:
  - name: headsetcontrol
    from: fedora:42
    modules:
      - type: containerfile
        containerfiles:
          - headsetcontrol

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      # copy static configurations
      # - source: usr
      #   destination: /usr
      # - source: rpm-gpg
      #   destination: /etc/pki/rpm-gpg
      # - source: yum.repos.d
      #   destination: /etc/yum.repos.d

  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      # Some GUI apps on host for better integration
      - gnome-clocks
      - gnome-tweaks
      - https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/fedora/fedora-42-x86_64/pgadmin4-9.5-1.fc42.noarch.rpm
      - nextcloud-client
      - nextcloud-client-nautilus
      - xournal

      # Tilix as default terminal
      - tilix
      - tilix-nautilus

      # Official docker-engine release
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

      # HP printer and scanner drivers
      - hplip
      - sane-backends-drivers-scanners
      - simple-scan

      # Needed by headsetcontrol
      - hidapi

      # Needed by Docker-OSX
      - libvirt
      - qemu-kvm

      # Logitech receiver
      - solaar
    remove:
      # default firefox removed in favor of flatpak
      - firefox
      - firefox-langpacks

  # - type: copy
  #   from: headsetcontrol
  #   src: /tmp/HeadsetControl/build/headsetcontrol
  #   dest: /usr/bin/headsetcontrol

  # - type: copy
  #   from: headsetcontrol
  #   src: /tmp/HeadsetControl/build/70-headsets.rules
  #   dest: /lib/udev/rules.d/70-headsets.rules

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: false
        install:
          - com.github.iwalton3.jellyfin-media-player
          - com.google.Chrome
          - com.mattjakeman.ExtensionManager
          - com.slack.Slack
          - com.visualstudio.code
          - dev.zed.Zed
          - eu.scarpetta.PDFMixTool
          - org.gnome.Calculator
          - org.gnome.Evince
          - org.gnome.Loupe
          - org.gnome.Snapshot
          - org.gnome.TextEditor
          - org.libreoffice.LibreOffice
          - org.mozilla.firefox
          - org.videolan.VLC
          - rest.insomnia.Insomnia
        remove:
          - org.gnome.Extensions
          - org.gnome.Totem

  # - type: gnome-extensions
  #   install:
  #     - AppIndicator and KStatusNotifierItem Support
  #     - Caffeine
  #     - Docker
  #     - HeadsetControl
  #     - Panel World Clock (Lite)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
