# image will be published to ghcr.io/<user>/<name>
name: fedora-bluebuild

# description will be included in the image's metadata
description: My personal Fedora Silverblue image based on universal-blue main image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# the tags to use
alt-tags:
  - latest

# stages. See: https://github.com/blue-build/cli/pull/173
stages:
  - name: headsetcontrol
    from: fedora:42
    modules:
      - type: containerfile
        containerfiles:
          - headsetcontrol

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      # copy static configurations
      #
      # copies config/files/usr into your image's /usr
      #
      # configuration you wish to end up in /etc/ on the booted system
      # should be added into /usr/etc/ as that is the proper "distro"
      # config directory on ostree. Read more in the files module's README
      - usr: /usr
      - rpm-gpg: /etc/pki/rpm-gpg
      - rpm-gpg: /usr/etc/pki/rpm-gpg
      - yum.repos.d: /etc/yum.repos.d
      - yum.repos.d: /usr/etc/yum.repos.d

  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      # Some GUI apps on host for better integration
      - gnome-clocks
      - nextcloud-client
      - nextcloud-client-nautilus
      - https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/fedora/fedora-39-x86_64/pgadmin4-8.6-1.fc39.noarch.rpm

      # Tilix as default terminal
      - tilix
      - tilix-nautilus

      # Official docker-engine release
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

      # HP printer and scanner drivers
      - hplip
      - sane-backends-drivers-scanners
      - simple-scan

      # Needed by headsetcontrol
      - hidapi

      # Needed by Docker-OSX
      - libvirt
      - qemu-kvm
    remove:
      # removing default gnome-terminal in favour of tilix
      - gnome-terminal
      - gnome-terminal-nautilus

      # default firefox removed in favor of flatpak
      - firefox
      - firefox-langpacks

  - type: copy
    from: headsetcontrol
    src: /tmp/HeadsetControl/build/headsetcontrol
    dest: /usr/bin/headsetcontrol

  - type: copy
    from: headsetcontrol
    src: /tmp/HeadsetControl/build/70-headsets.rules
    dest: /lib/udev/rules.d/70-headsets.rules

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.github.iwalton3.jellyfin-media-player
        - com.google.Chrome
        - com.mattjakeman.ExtensionManager
        - com.slack.Slack
        - com.visualstudio.code
        - eu.scarpetta.PDFMixTool
        - org.gnome.Evince
        - org.gnome.Loupe
        - org.gnome.Snapshot
        - org.gnome.TextEditor
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - org.videolan.VLC
        - rest.insomnia.Insomnia
      remove:
        - org.gnome.Extensions
        - org.gnome.Totem

  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
      - Caffeine
      - Docker
      - HeadsetControl
      - Panel World Clock (Lite)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
