WORKDIR /tmp
RUN dnf group install -y "development-tools"
RUN dnf install -y cmake hidapi-devel g++
RUN git clone https://github.com/Sapd/HeadsetControl && \
    cd HeadsetControl && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make
